try{
    let num = 10/4;
    console.log(num);
    console.log(Ans1);
}
catch(err){
    console.log("Error Caught: ", err)
}